# Site Settings
baseurl: 		""
title: 			sorpa'as plat

name: 			sorpa'as plat
description: 	The website of sorpa'as
url: 			"http://sorpaas.com"

paginate: 		3
paginate_path: 	"blog/page/:num"

twitter: 		sorpaas
email: 			me@sorpaas.com

analytics: 		UA-48084244-4

copyright: 		Copyright 2014 sorpa'as.

# Build Settings
permalinks: 	pretty
markdown: kramdown
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
