title: sorpa'as plat
permalink: /:categories/:title
pygments: true
version: "1.0.4-beta"
markdown: redcarpet
exclude:
  - "README.md"
  - "Gruntfile.coffee"
  - "Rakefile"
  - "node_modules"
  - "*.psd"
