# Site Settings
baseurl: 		""
title: 			sorpa'as plat

name: 			sorpa'as plat
description: 	The website of sorpa'as
url: 			"http://sorpaas.com"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		sorpaas
email: 			me@sorpaas.com

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		Copyright 2014 sorpa'as.	

# Build Settings
permalinks: 	pretty
markdown: kramdown