# Site Settings
baseurl       : ""
title         : sorpa'as plat

name          : sorpa'as plat
description   : The website of sorpa'as
url           : "http://sorpaas.com"

# paginate      : 3
# paginate_path : "blog/page/:num"

twitter       : sorpaas
email         : me@sorpaas.com

analytics     :

copyright     : Copyright 2014 sorpa'as plat.

# Build Settings
permalinks    : pretty
markdown      : kramdown
exclude       : ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Guardfile']
collections   :
  projects    :
    output    : true
